version: '3'
services:
    app:
        image: 172396373649.dkr.ecr.eu-central-1.amazonaws.com/signageos/docker-node:16-alpine-build
        volumes:
            - .:/app
        working_dir: /app
        env_file:
            - ~/.signageos/npm.env
        environment:
          TZ: "Europe/Prague"
        command: tail -f /dev/null
